# See full config at https://github.com/backup-manager/symfony
bm_backup_manager:
    database:
        development:
            dsn: '%env(resolve:DATABASE_URL)%'
    storage:
        local:
            type: Local
            root: /Users/vo2group/Documents/Personnel/BACV78/symfony/bacv/backup_serveur
