easy_admin:
  site_name: 'BACV - Derrière le bureau'
  design:
    assets:
      css:
          - 'bundles/easyadmin/bootstrap-all.css'
      js:
          # By default, EasyAdminBundle embeds a limited version of Bootstrap JS.
          # For collapsible form filters to work, a full version should be added:
          - 'bundles/easyadmin/bootstrap-all.js'
    form_theme: # Both themes are for ckeditor integration
            - "@EasyAdmin/form/bootstrap_4.html.twig"
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
    brand_color: '#084a57' #d6eaf8
    menu:
      - {label: 'Retour Site BACV', route: 'homepage', icon: 'arrow-up'}
      - {label: 'Gestion des Articles et des Catégories', permission: ROLE_SUPER_ADMIN, icon: 'newspaper-o', children: ['Articles', 'Categories']}
      - label: 'Gestion des Joueurs, des Clubs et des Equipes'
        icon: 'users'
        children:
          - {entity: 'Joueurs'}
          - {entity: 'Equipes', permission: 'ROLE_SUPER_ADMIN'}
          - {entity: 'Equipes_Veteran', label: 'Equipes Vétéran'}
          - {entity: 'Clubs'}
          - {entity: 'CategorieAge'}
          - {entity: 'Status', label: 'Statut Inscription'}
      - label: 'Gestion des Tournois'
        permission: ROLE_SUPER_ADMIN
        icon: 'users'
        children:
          - {entity: 'Tournois'}
          - {entity: 'TournoisUser', label: 'Joueurs-Tournois'}
      - label: 'Gestion des Interclubs et des Saisons'
        icon: 'users'
        children:
          - {entity: 'Saison'}
          - {entity: 'Interclubs'}
          - {entity: 'InterclubsVeteran', label: 'Interclubs Vétéran'}
          - {entity: 'Lieu', label: 'Lieux des rencontres'}
      - label: 'Gestion des Sondages'
        icon: 'newspaper-o'
        children:
          - {entity: 'Question'}
          - {entity: 'Sondage'}
          - {entity: 'Reponse', label: 'Réponses'}
      - label: 'Gestion Doodle'
        icon: 'newspaper-o'
        children:
          - {entity: 'Doodle'}
          - {entity: 'Item'}
          - {entity: 'QcmValue', label: 'Valeurs de QCM'}
          - {entity: 'Personne'}
          - {entity: 'LienDoodle'}
  entities:
    Articles:
      class: App\Entity\Article
      form:
        fields:
          - {property: 'content', label: 'Contenu Article', type: 'fos_ckeditor'}
          - {property: 'title', label: 'Titre'}
          - {property: 'auteur', label: 'Auteur'}
          - {property: 'lastUpdateDate', label: 'Date MAJ'}
          - {property: 'excerpt', label: 'Extrait'}
          - {property: 'isPublished', label: 'Publié'}
          - {property: 'pictures', type: 'file_upload', type_options: {
              upload_dir: 'public/uploads/article/',
              multiple: true,
              download_path: 'uploads/article/'
            }}
      list:
        fields:
          - {property: 'title', label: 'Titre'}
          - {property: 'excerpt', label: 'Extrait'}
          - {property: 'isPublished', label: 'Publié'}
          - {property: 'lastUpdateDate', label: 'Date MAJ'}
          - {property: 'pictures', label: 'Images'}
          - {property: 'auteur', label: 'Auteur'}

    Clubs:
      class: App\Entity\Club
      role: 'ROLE_SUPER_ADMIN'
    Categories:
      class: App\Entity\Category
    CategorieAge:
      class: App\Entity\AgeCategory
    Joueurs:
      class: App\Entity\User
      form:
        fields:
          - {property: 'username', label: 'Identifiant'}
          - {property: 'active', label: 'Inscrit cette saison'}
          - {property: 'email', type: 'email'}
          - {property: 'teamManaged', label: 'Equipe gérée en tant que capitaine'}
          - {property: 'teamVeteranManaged', label: 'Equipe Vétéran gérée en tant que capitaine'}
          - {property: 'mobile', type: 'tel'}
          - {property: 'team', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Team' } }
          - {property: 'teamVeteran', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\TeamVeteran' } }
          - {property: 'club', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Club' } }
          - {property: 'category', label: 'Groupe', type: 'choice', type_options: {
              choices: { 'Aucun': null, 'Compétiteur': 'Compétiteur', 'Loisir': 'Loisir', 
              'Loisir avec Interclub': 'Loisir avec Interclub','Jeune': 'Jeune'}
              }
            }
      list:
        fields: [{ property: 'firstName', label: 'Prénom' }, { property: 'lastName', label: 'Nom' }, 
          'email', { property: 'active', label: 'Inscrit' }, {property: 'mobile', type: 'tel'},
          { property: 'team', label: 'Equipe IC' }, {property: 'category', label: 'Groupe'}]
        sort: ['lastName', 'ASC']
      search:
        fields: ['firstName', 'lastName', 'email']
    Equipes:
      class: App\Entity\Team
    Status:
      class: App\Entity\Status
    Equipes_Veteran:
      class: App\Entity\TeamVeteran
    Saison:
      class: App\Entity\Saison
    Tournois:
      class: App\Entity\Tournoi
    TournoisUser:
      class: App\Entity\TournoiUser
    Interclubs:
      class: App\Entity\Interclub
    InterclubsVeteran:
      class: App\Entity\InterclubVeteran
    Lieu:
      class: App\Entity\Lieu
    Question:
      class: App\Entity\Question
      form:
        fields:
          - {property: 'name', label: 'Titre'}
          - {property: 'type', label: 'Type'}
          - {property: 'active', label: 'Actif ?'}
          - {property: 'label', label: 'Question'}
          - {property: 'choix', label: 'Réponses'}
          - {property: 'sondages', label: 'Sondages liés'}
      list:
        fields:
          - {property: 'name', label: 'Titre'}
          - {property: 'type', label: 'Type'}
          - {property: 'active', label: 'Actif ?'}
          - {property: 'label', label: 'Question'}
          - {property: 'sondages', label: 'Sondages liés'}
    Sondage:
      class: App\Entity\Sondage
    Reponse:
      class: App\Entity\Reponse
    Doodle:
      class: App\Entity\Doodle
      form:
        fields:
          - {property: 'md5', type: 'text', label: 'Clé pour le lien doodle', type_options: { disabled: true }}
          - {property: 'name', label: 'Nom'}
          - {property: 'description', label: 'Description'}
          - {property: 'beginDate', label: 'Début'}
          - {property: 'endDate', label: 'Fin'}
          - {property: 'maxPersonnes', label: 'Nombre maximum de personnes'}
          - {property: 'active', label: 'Actif'}
          - {property: 'qcmValues', label: 'Valeurs du QCM'}
          - {property: 'type', label: 'Type', type: 'choice', type_options: {
              choices: { 'QCM': 'qcm', 'Cases à cocher': 'checkbox', 'Saisie libre': 'text', 'Nombre': 'number' },
              required: true
              }
            }
      list:
        fields:
          - {property: 'id', label: 'id'}
          - {property: 'md5', label: 'Clé'}
          - {property: 'name', label: 'Nom'}
          - {property: 'description', label: 'Libellé'}
          - {property: 'maxPersonnes', label: 'Maximum'}
          - {property: 'active', label: 'Actif ?'}
          - {property: 'typeValue', label: 'Type' }
    Item:
      class: App\Entity\Item
    QcmValue:
      class: App\Entity\QcmValue
    Personne:
      class: App\Entity\Personne
    LienDoodle:
      class: App\Entity\LienDoodle